### ISSUE TITLE
Hardcoded defaults

### ISSUE THREAD

**Issue by wiobber** [m8rex/rumbas#25]
Can/does the code have hardcoded defaults (for options in the defaults/ folder)?

Now it seems when new options are added, the defaults folder has to be updated to provide a value for the new option.
That breaks compatibility ...

**Comment by jhoobergs** [comment]
The goal is that you will always be able to find the used value somewhere in your repo, so by design there are no defaults in rumbas.

When people upgrade to a new version, they will need to read the upgrade guide and make sure that they add the extra defaults.

It would probably be best to add an `.rumbas_version` file in each repo that specifies which version should be used.

**Comment by jhoobergs** [comment]
`.rumbas-rc.yaml`  file and the `update-repo` command handle this.
